# Generated by Django 3.1.7 on 2021-03-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('is_employed', models.BooleanField()),
                ('company', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='company.companymodel')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
