# Generated by Django 3.1.7 on 2021-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210316_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
